spring:
  application:
    name: linkpulse-backend
  config:
    import: "optional:file:.env[.properties]"
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/linkpulse?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${SPRING_KAFKA_SECURITY_PROTOCOL:SASL_SSL}
      sasl.mechanism: ${SPRING_KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${SPRING_KAFKA_SASL_JAAS_CONFIG:}
    ssl:
      trust-store-type: PEM
      trust-store-location: ${KAFKA_CA_CERT_PATH:file:src/main/resources/ca.pem}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: linkpulse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:your.email@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:nehq rzqj pmvg pgyu}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  
# Application Specific Properties
app:
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expirationMs: ${APP_JWT_EXPIRATIONMS:86400000}
  base-url: ${APP_BASE_URL:http://localhost:8080/}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:5174}
